version: '3.8'

services:
  dashboard:
    image: bemeeker/themancavedashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mancave-dashboard
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
          # Google OAuth files (if using file-based credentials)
          - ${GOOGLE_CREDENTIALS_PATH:-./credentials.json}:/app/credentials.json:ro
          - ${GOOGLE_TOKEN_PATH:-./token.json}:/app/token.json:ro
          # Mount config directory (better than file mount for editors that atomic-write)
          - ${CONFIG_PATH:-./config.json}:/app/external-config.json:delegated
          # Mount photos directory from host machine
          - ${PHOTOS_PATH:-./public/photos}:/usr/share/nginx/html/photos:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s


