name: Continuous Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      frontend_repository: ${{ steps.vars.outputs.frontend_repository }}
      backend_repository: ${{ steps.vars.outputs.backend_repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute vars
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "frontend_repository=bemeeker/themancavedashboard-frontend" >> "$GITHUB_OUTPUT"
          echo "backend_repository=bemeeker/themancavedashboard-backend" >> "$GITHUB_OUTPUT"

  build-and-push-frontend:
    needs: vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ needs.vars.outputs.frontend_repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ needs.vars.outputs.frontend_repository }}:buildcache
          cache-to: type=registry,ref=${{ needs.vars.outputs.frontend_repository }}:buildcache,mode=max

  build-and-push-backend:
    needs: vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ needs.vars.outputs.backend_repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile.backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ needs.vars.outputs.backend_repository }}:buildcache
          cache-to: type=registry,ref=${{ needs.vars.outputs.backend_repository }}:buildcache,mode=max
